### ISSUE TITLE
Split off xenon plugins

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#48]
Ditch all the XENON experimental software from strax ;)

**Comment by tunnell** [comment]
Specifically, move xenon folder out into its own repository.

**Comment by tunnell** [comment]
bump

**Comment by JelleAalbers** [comment]
After the current open PRs are merged, and after moving the stuff in `notebooks` into `xenon`, I'll try to do this with filter_branch (https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/).

This leaves two questions:
  * Will the new repo be called `straxen` or `xestrax`? I'm leaning towards `straxen`, since `xestrax` would have xenon it it twice.
  * Host it in the nT or 1T github? Even though the plugins are geared towards 1T reanalysis, I guess nT would make most sense, since it is the next software generation.

**Comment by JelleAalbers** [comment]
This has been done in #107
