### ISSUE TITLE
What should be the expected behavior for iterable-type options

### ISSUE THREAD

**Issue by WenzDaniel** [AxFoundation/strax#494]
In strax the behavior for iterable as options defaults/values can be a bit flaky. E.g. the lineage changes when specifying the very same setting as a tuple and as a list (see attached image). We may want to consider to convert all those simple iterables list/tuple/arrays into the same kind of format during initialization of the corresponding option.  

Before moving in this direction though I would like to hear some other opinions. 

![example](https://user-images.githubusercontent.com/43881800/127334798-d596a524-b165-4889-9ce5-df6f259b7ed5.png)

**Comment by jorana** [comment]
I disagree that this is flaky. It's to be expected and list or tuples can mean different things and such be treated as such. Think of the many instances in CMT where `istinstance(bla, tuple)` is used.

**Comment by WenzDaniel** [comment]
> Think of the many instances in CMT where istinstance(bla, tuple) is used.

I know that we are using it a lot, but I agree with Andrii, that from a user perspective this is very unintuitive and error prone. Especially for the simulation side where settings may change more frequently. 

I think we should enforce every setting to be a tuple as its immutable. I do not see any con's in this approach. E.g. CMT only differentiates between strings and tuples.

**Comment by jorana** [comment]
> I think we should enforce every setting to be a tuple as its immutable

I absolutely agree on this 😉, a potential follow up of this PR would be raising a warning when a mutable object such as a dict or a list is used as a config. Luckily we have been already enforcing this for straxen. (Strictly speaking, we should than also warn for strings as they are mutable too.)

> perspective this is very unintuitive and error prone.

Right, perhaps it's a bit too much of a user to recognize the difference between tuples and lists. On the other hand, it's not that error prone, it's only when people start changing configs manually. 

It's a slippery slope if we interpret too much what a user might have meant instead of what the user specified (okay perhaps tuples and lists are not _that_ slippery but you get the idea :wink:), for instance would we want a user to allow `range(3)` `[0, 1, 2]`, `(0, 1, 2)`, `np.array([0, 1, 2])`,  to all result in the same lineage? Perhaps even `{0 : None, 1 : None, 2 : None}`? I think that would be potetially quite slow (compared to a simple `sha1` on the object) and hardcoded if we'd go for such an approach.

**Comment by JelleAalbers** [comment]
Strax already converts lists to tuples when computing hashes, but (700) isn't a tuple, it's an integer with parentheses around it :-)

![Screenshot from 2021-08-07 12-45-34](https://user-images.githubusercontent.com/4354311/128612216-2c09b1c1-0aa7-44f9-ad81-a45ab1d98f62.png)

The lineage hash is computed via [hashablize](https://github.com/AxFoundation/strax/blob/master/strax/utils.py#L255|hashablize), which will recursively convert anything that cannot be `hash`ed (list, dicts, sets, numpy arrays, etc) to tuples, or die trying. Even things like lists inside tuples are converted.

You're right though that mutable defaults for settings (or anything else) are dangerous.

**Comment by WenzDaniel** [comment]
Hi Jelle thanks a lot for clarification. I was a bit quick in jumping to conclusions. We had an issue with our simulation data for which it was observed that even though the data was made it did not appear as stored in strax. But we learned already that it was due to the fact that the user-defined run_id contained a minus sign.
