### ISSUE TITLE
S3 backend_key

### ISSUE THREAD

**Issue by tunnell** [AxFoundation/strax#72]
Somebody (probably me) should look at these Backend keys for the I/O and how that translates to the S3-enabled backends.  The issue is that there are buckets, folders, and files, but the folder/file location is just one S3 key.  This leads to confusion.  Need to rethink this.

**Comment by tunnell** [comment]
Done

**Comment by tunnell** [comment]
Wrong one.

**Comment by JelleAalbers** [comment]
I guess the main question was if the S3 authentication info should be part of the backend key. I initially thought so, because then you didn't have to provide them while initializing an S3-enabled frontend (like the runs db interface). However, this would mean you have to store them in the runs db, which would make them hard to change, and force everyone to use the same key with the same permissions.

The current approach (auth info provided on init) makes more sense to me. So from my perspective we can close this.
